import React from 'react';
import { 
  Network, 
  Database, 
  Cpu, 
  ArrowDown, 
  Layers, 
  Zap, 
  CheckCircle,
  HardDrive,
  BarChart3,
  Server
} from 'lucide-react';

function Architecture() {
  return (
    <div className="space-y-8 fade-in">
      {/* Title Bar */}
      <div>
        <h2 className="text-2xl font-bold text-gray-100 uppercase tracking-wide">Scalability Architecture</h2>
        <p className="text-sm text-cyber-textMuted">Enterprise-grade big data ingestion & real-time threat analysis blueprint</p>
      </div>

      {/* Visual Ingestion Pipeline Flowchart */}
      <div className="bg-cyber-card border border-cyber-border rounded-xl p-6 relative overflow-hidden">
        <div className="flex items-center gap-2 border-b border-cyber-border pb-3 mb-6">
          <Network className="h-4 w-4 text-cyber-success" />
          <h4 className="font-semibold text-xs uppercase font-mono tracking-wide text-gray-200">Real-Time Ingestion Pipeline Blueprint</h4>
        </div>

        {/* Vertical Flow Diagram with SVG arrows */}
        <div className="flex flex-col items-center justify-center space-y-3 py-4 max-w-lg mx-auto font-mono text-xs text-center">
          
          {/* Node 1: CSV logs / APIs */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-info transition-all duration-200 shadow-lg">
            <span className="text-[10px] text-cyber-info uppercase block mb-1">Data Source</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <HardDrive className="h-4 w-4" />
              CSV Access Logs & API Audits
            </div>
            <span className="text-[9px] text-cyber-textMuted">Raw JSON/CSV access events generated by apps</span>
          </div>

          <ArrowDown className="h-6 w-6 text-cyber-success animate-bounce" />

          {/* Node 2: Kafka message broker */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-success transition-all duration-200 shadow-lg glow-emerald">
            <span className="text-[10px] text-cyber-success uppercase block mb-1">Message Buffer</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <Server className="h-4 w-4 text-cyber-success" />
              Apache Kafka Clustered Broker
            </div>
            <span className="text-[9px] text-cyber-textMuted">High-throughput, multi-partition topic streams</span>
          </div>

          <ArrowDown className="h-6 w-6 text-cyber-success" />

          {/* Node 3: Spark Streaming processor */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-warning transition-all duration-200 shadow-lg">
            <span className="text-[10px] text-cyber-warning uppercase block mb-1">Stream Processing</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <Cpu className="h-4 w-4 text-cyber-warning" />
              Apache Spark Structured Streaming
            </div>
            <span className="text-[9px] text-cyber-textMuted">Micro-batch ingestion & behavioral context joints</span>
          </div>

          <ArrowDown className="h-6 w-6 text-cyber-success" />

          {/* Node 4: Risk scoring engine */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-purple transition-all duration-200 shadow-lg glow-purple">
            <span className="text-[10px] text-cyber-purple uppercase block mb-1">Risk Evaluation Engine</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <Layers className="h-4 w-4 text-cyber-purple" />
              SentinelGuard Risk Core (Scikit-Learn/Rules)
            </div>
            <span className="text-[9px] text-cyber-textMuted">Evaluates Z-Scores, Isolation Forest & heuristic metrics</span>
          </div>

          <ArrowDown className="h-6 w-6 text-cyber-success" />

          {/* Node 5: PostgreSQL storage */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-info transition-all duration-200 shadow-lg">
            <span className="text-[10px] text-cyber-info uppercase block mb-1">Database Layer</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <Database className="h-4 w-4 text-cyber-info" />
              Enterprise PostgreSQL Cluster
            </div>
            <span className="text-[9px] text-cyber-textMuted">Stores indexed alerts, user profiles, & computed baselines</span>
          </div>

          <ArrowDown className="h-6 w-6 text-cyber-success" />

          {/* Node 6: Dashboard portal */}
          <div className="w-full bg-cyber-bg border border-cyber-border rounded-lg p-3 hover:border-cyber-success transition-all duration-200 shadow-lg">
            <span className="text-[10px] text-cyber-success uppercase block mb-1">Visualization Portal</span>
            <div className="flex items-center justify-center gap-2 text-cyber-textActive font-bold">
              <BarChart3 className="h-4 w-4 text-cyber-success" />
              SentinelGuard Web UI Dashboard
            </div>
            <span className="text-[9px] text-cyber-textMuted">Provides real-time alert feed & analyst workspace</span>
          </div>

        </div>
      </div>

      {/* Explanatory Documentation: Processing 1M+ Events/Day */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono text-xs">
        {/* Math & Capacity Analysis */}
        <div className="bg-cyber-card border border-cyber-border rounded-xl p-5 space-y-4">
          <div className="flex items-center gap-2 border-b border-cyber-border pb-3">
            <Zap className="h-4 w-4 text-cyber-warning animate-pulse" />
            <h4 className="font-semibold text-sm uppercase tracking-wide text-gray-200">Throughput Calculations</h4>
          </div>

          <div className="space-y-3 text-gray-300 leading-relaxed">
            <p>
              To process <span className="text-cyber-success font-bold">1 Million events per day</span>, the infrastructure must achieve the following milestones:
            </p>

            <ul className="space-y-2.5 pl-4 list-disc text-cyber-textMuted">
              <li>
                <span className="text-cyber-textActive font-bold">Average Throughput:</span> 1,000,000 events / 86,400 seconds = <span className="text-cyber-success font-bold">~11.57 events per second (EPS)</span>.
              </li>
              <li>
                <span className="text-cyber-textActive font-bold">Peak Traffic Handling:</span> Assuming standard business spikes (10x average traffic), the system must process <span className="text-cyber-warning font-bold">~120 EPS</span>.
              </li>
              <li>
                <span className="text-cyber-textActive font-bold">Latency SLA:</span> Alerts should compile on the React UI within <span className="text-cyber-info font-bold">&lt; 1,500ms</span> of the initial query.
              </li>
            </ul>

            <p className="text-[11px] border-t border-cyber-border/30 pt-3 text-cyber-textMuted">
              Because 120 EPS is extremely low for modern stream processors, a single lightweight server can process the logic. However, clustering guarantees zero-data-loss SLAs.
            </p>
          </div>
        </div>

        {/* Scalability Strategies */}
        <div className="bg-cyber-card border border-cyber-border rounded-xl p-5 space-y-4">
          <div className="flex items-center gap-2 border-b border-cyber-border pb-3">
            <CheckCircle className="h-4 w-4 text-cyber-success" />
            <h4 className="font-semibold text-sm uppercase tracking-wide text-gray-200">Clustering & Fault Tolerance</h4>
          </div>

          <div className="space-y-3.5 text-cyber-textMuted leading-relaxed">
            <div>
              <span className="text-cyber-textActive font-bold block mb-1">1. Message Buffering (Kafka)</span>
              <p className="text-[11px]">
                Kafka topic partitioning allows scaling out. If the DB goes offline for updates, Kafka buffers incoming events for up to 7 days, guaranteeing no loss of access audits.
              </p>
            </div>

            <div>
              <span className="text-cyber-textActive font-bold block mb-1">2. Horizontal Compute scaling (Spark & Risk core)</span>
              <p className="text-[11px]">
                Spark processes incoming logs in parallel worker nodes. Risk calculations (Z-Scores & Isolation Forest execution) run stateless, letting us spin up container nodes on demand.
              </p>
            </div>

            <div>
              <span className="text-cyber-textActive font-bold block mb-1">3. Database Replication (PostgreSQL)</span>
              <p className="text-[11px]">
                PostgreSQL is structured with high-performance indexes. Dashboard reads are routed to Read-Replicas, while incoming event writes target the primary master database write cluster.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Architecture;
